### ISSUE TITLE
Support normal chat functions

### ISSUE THREAD

**Issue by veiz** [leancloud/leanchat-webapp#1]
like upload file, avatar, timestamp and group chat. Nice to see if it can be integrate this function into my hybrid apps.

**Comment by veiz** [comment]
Found this, https://github.com/leancloud/leanmessage-demo . close issue

**Comment by lzwjava** [comment]
:+1: 

上传文件、头像、群聊都是可以实现的。文档：https://leancloud.cn/docs/js_realtime.html
